// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ActionData
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Joint : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Joint GetRootAsJoint(ByteBuffer _bb) { return GetRootAsJoint(_bb, new Joint()); }
  public static Joint GetRootAsJoint(ByteBuffer _bb, Joint obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Joint __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float W { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float X { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Y { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Z { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public string Name { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<ActionData.Joint> CreateJoint(FlatBufferBuilder builder,
      float w = 0.0f,
      float x = 0.0f,
      float y = 0.0f,
      float z = 0.0f,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartTable(5);
    Joint.AddName(builder, nameOffset);
    Joint.AddZ(builder, z);
    Joint.AddY(builder, y);
    Joint.AddX(builder, x);
    Joint.AddW(builder, w);
    return Joint.EndJoint(builder);
  }

  public static void StartJoint(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddW(FlatBufferBuilder builder, float w) { builder.AddFloat(0, w, 0.0f); }
  public static void AddX(FlatBufferBuilder builder, float x) { builder.AddFloat(1, x, 0.0f); }
  public static void AddY(FlatBufferBuilder builder, float y) { builder.AddFloat(2, y, 0.0f); }
  public static void AddZ(FlatBufferBuilder builder, float z) { builder.AddFloat(3, z, 0.0f); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(4, nameOffset.Value, 0); }
  public static Offset<ActionData.Joint> EndJoint(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ActionData.Joint>(o);
  }
}


}
