// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ActionData
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Squat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Squat GetRootAsSquat(ByteBuffer _bb) { return GetRootAsSquat(_bb, new Squat()); }
  public static Squat GetRootAsSquat(ByteBuffer _bb, Squat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Squat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Status { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<ActionData.Squat> CreateSquat(FlatBufferBuilder builder,
      float status = 0.0f) {
    builder.StartTable(1);
    Squat.AddStatus(builder, status);
    return Squat.EndSquat(builder);
  }

  public static void StartSquat(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddStatus(FlatBufferBuilder builder, float status) { builder.AddFloat(0, status, 0.0f); }
  public static Offset<ActionData.Squat> EndSquat(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ActionData.Squat>(o);
  }
}


}
