// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ActionData
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Stand : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Stand GetRootAsStand(ByteBuffer _bb) { return GetRootAsStand(_bb, new Stand()); }
  public static Stand GetRootAsStand(ByteBuffer _bb, Stand obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Stand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Mode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<ActionData.Stand> CreateStand(FlatBufferBuilder builder,
      float mode = 0.0f) {
    builder.StartTable(1);
    Stand.AddMode(builder, mode);
    return Stand.EndStand(builder);
  }

  public static void StartStand(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddMode(FlatBufferBuilder builder, float mode) { builder.AddFloat(0, mode, 0.0f); }
  public static Offset<ActionData.Stand> EndStand(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ActionData.Stand>(o);
  }
}


}
