// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ApplicationClient
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Client : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Client GetRootAsClient(ByteBuffer _bb) { return GetRootAsClient(_bb, new Client()); }
  public static Client GetRootAsClient(ByteBuffer _bb, Client obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Client __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetIdArray() { return __p.__vector_as_array<byte>(4); }
  public bool UseJson { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<ApplicationClient.Client> CreateClient(FlatBufferBuilder builder,
      StringOffset idOffset = default(StringOffset),
      bool useJson = false) {
    builder.StartTable(2);
    Client.AddId(builder, idOffset);
    Client.AddUseJson(builder, useJson);
    return Client.EndClient(builder);
  }

  public static void StartClient(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
  public static void AddUseJson(FlatBufferBuilder builder, bool useJson) { builder.AddBool(1, useJson, false); }
  public static Offset<ApplicationClient.Client> EndClient(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ApplicationClient.Client>(o);
  }
  public static void FinishClientBuffer(FlatBufferBuilder builder, Offset<ApplicationClient.Client> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedClientBuffer(FlatBufferBuilder builder, Offset<ApplicationClient.Client> offset) { builder.FinishSizePrefixed(offset.Value); }
}


}
