// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Sensor
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct SensorFrame : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static SensorFrame GetRootAsSensorFrame(ByteBuffer _bb) { return GetRootAsSensorFrame(_bb, new SensorFrame()); }
  public static SensorFrame GetRootAsSensorFrame(ByteBuffer _bb, SensorFrame obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SensorFrame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string SensorType { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSensorTypeBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetSensorTypeBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetSensorTypeArray() { return __p.__vector_as_array<byte>(4); }
  public string SensorId { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSensorIdBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetSensorIdBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetSensorIdArray() { return __p.__vector_as_array<byte>(6); }
  public string Version { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVersionBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetVersionBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetVersionArray() { return __p.__vector_as_array<byte>(8); }
  public ImuData.Imu? Imu { get { int o = __p.__offset(10); return o != 0 ? (ImuData.Imu?)(new ImuData.Imu()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Sensor.SensorFrame> CreateSensorFrame(FlatBufferBuilder builder,
      StringOffset sensorTypeOffset = default(StringOffset),
      StringOffset sensorIdOffset = default(StringOffset),
      StringOffset versionOffset = default(StringOffset),
      Offset<ImuData.Imu> imuOffset = default(Offset<ImuData.Imu>)) {
    builder.StartTable(4);
    SensorFrame.AddImu(builder, imuOffset);
    SensorFrame.AddVersion(builder, versionOffset);
    SensorFrame.AddSensorId(builder, sensorIdOffset);
    SensorFrame.AddSensorType(builder, sensorTypeOffset);
    return SensorFrame.EndSensorFrame(builder);
  }

  public static void StartSensorFrame(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddSensorType(FlatBufferBuilder builder, StringOffset sensorTypeOffset) { builder.AddOffset(0, sensorTypeOffset.Value, 0); }
  public static void AddSensorId(FlatBufferBuilder builder, StringOffset sensorIdOffset) { builder.AddOffset(1, sensorIdOffset.Value, 0); }
  public static void AddVersion(FlatBufferBuilder builder, StringOffset versionOffset) { builder.AddOffset(2, versionOffset.Value, 0); }
  public static void AddImu(FlatBufferBuilder builder, Offset<ImuData.Imu> imuOffset) { builder.AddOffset(3, imuOffset.Value, 0); }
  public static Offset<Sensor.SensorFrame> EndSensorFrame(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Sensor.SensorFrame>(o);
  }
  public static void FinishSensorFrameBuffer(FlatBufferBuilder builder, Offset<Sensor.SensorFrame> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedSensorFrameBuffer(FlatBufferBuilder builder, Offset<Sensor.SensorFrame> offset) { builder.FinishSizePrefixed(offset.Value); }
}


}
