// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Input
{

public enum MessageType : short
{
  None = 0,
  ApplicationClient = 1,
  ApplicationControl = 2,
  Pose = 3,
  SensorFrame = 4,
  SensorClient = 5,
  SensorControl = 6,
};


}
