// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PoseData
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Point : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Point GetRootAsPoint(ByteBuffer _bb) { return GetRootAsPoint(_bb, new Point()); }
  public static Point GetRootAsPoint(ByteBuffer _bb, Point obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Point __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Y { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Z { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Score { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public string Name { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<PoseData.Point> CreatePoint(FlatBufferBuilder builder,
      float x = 0.0f,
      float y = 0.0f,
      float z = 0.0f,
      float score = 0.0f,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartTable(5);
    Point.AddName(builder, nameOffset);
    Point.AddScore(builder, score);
    Point.AddZ(builder, z);
    Point.AddY(builder, y);
    Point.AddX(builder, x);
    return Point.EndPoint(builder);
  }

  public static void StartPoint(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddX(FlatBufferBuilder builder, float x) { builder.AddFloat(0, x, 0.0f); }
  public static void AddY(FlatBufferBuilder builder, float y) { builder.AddFloat(1, y, 0.0f); }
  public static void AddZ(FlatBufferBuilder builder, float z) { builder.AddFloat(2, z, 0.0f); }
  public static void AddScore(FlatBufferBuilder builder, float score) { builder.AddFloat(3, score, 0.0f); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(4, nameOffset.Value, 0); }
  public static Offset<PoseData.Point> EndPoint(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PoseData.Point>(o);
  }
}


}
